version: '3.2'

services:
   db:
     image: mysql:5.7
     volumes:
       - /mnt/data/websites/website1/mssql:/var/lib/mysql
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: supersecretpassword
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wp-content:/var/www/html/wp-content
     restart: unless-stopped
     ports:
       - 11180:80
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

   ssh:
     depends_on:
       - wordpress
     image: sshtunnel:latest
     volumes:
       - /mnt/data/websites/website1/ssh:/ssh
     restart: unless-stopped
     environment:
       PATH_TO_SSH_KEY: /ssh/id_rsa
       SSH_HOST: 132.47.144.108
       SSH_PORT: 22501
       CONTAINER_HOST: wordpress
       CONTAINER_PORT: 80

   autoheal:
     restart: always
     image: willfarrell/autoheal
     environment:
       - AUTOHEAL_CONTAINER_LABEL=all
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock